jasmine.DEFAULT_TIMEOUT_INTERVAL = 10000

export * from './callSpec'
export * from './executeSpec'
export * from './formatSpec'
export * from './imageHomeSpec'
export * from './executionContextSpec'
export * from './testAssetsSpec'
export * from './util/cliSpec'
export * from './util/htmlSpec'
export * from './util/fileSpec'
export * from './util/imageBuiltInSpec'
export * from './util/imageCompareSpec'
export * from './util/imageExtractInfoSpec'
export * from './util/miscSpec'
export * from './util/supportSpec'
