/* auto-generated file using command `npx ts-node scripts/generateImEnums.ts` */
export enum IMColorspace {
  'CIELab' = 'CIELab',
  'CMY' = 'CMY',
  'CMYK' = 'CMYK',
  'Gray' = 'Gray',
  'HCL' = 'HCL',
  'HCLp' = 'HCLp',
  'HSB' = 'HSB',
  'HSI' = 'HSI',
  'HSL' = 'HSL',
  'HSV' = 'HSV',
  'HWB' = 'HWB',
  'Lab' = 'Lab',
  'LCH' = 'LCH',
  'LCHab' = 'LCHab',
  'LCHuv' = 'LCHuv',
  'LinearGray' = 'LinearGray',
  'LMS' = 'LMS',
  'Log' = 'Log',
  'Luv' = 'Luv',
  'OHTA' = 'OHTA',
  'Rec601YCbCr' = 'Rec601YCbCr',
  'Rec709YCbCr' = 'Rec709YCbCr',
  'RGB' = 'RGB',
  'scRGB' = 'scRGB',
  'sRGB' = 'sRGB',
  'Transparent' = 'Transparent',
  'xyY' = 'xyY',
  'XYZ' = 'XYZ',
  'YCbCr' = 'YCbCr',
  'YDbDr' = 'YDbDr',
  'YCC' = 'YCC',
  'YIQ' = 'YIQ',
  'YPbPr' = 'YPbPr',
  'YUV' = 'YUV',
}
