/* auto-generated file using command `npx ts-node scripts/generateImEnums.ts` */
export enum IMCompress {
  'B44A' = 'B44A',
  'B44' = 'B44',
  'BZip' = 'BZip',
  'DXT1' = 'DXT1',
  'DXT3' = 'DXT3',
  'DXT5' = 'DXT5',
  'Fax' = 'Fax',
  'Group4' = 'Group4',
  'JBIG1' = 'JBIG1',
  'JBIG2' = 'JBIG2',
  'JPEG2000' = 'JPEG2000',
  'JPEG' = 'JPEG',
  'LosslessJPEG' = 'LosslessJPEG',
  'Lossless' = 'Lossless',
  'LZMA' = 'LZMA',
  'LZW' = 'LZW',
  'None' = 'None',
  'Piz' = 'Piz',
  'Pxr24' = 'Pxr24',
  'RLE' = 'RLE',
  'RunlengthEncoded' = 'RunlengthEncoded',
  'WebP' = 'WebP',
  'ZipS' = 'ZipS',
  'Zip' = 'Zip',
  'Zstd' = 'Zstd',
}
