/* auto-generated file using command `npx ts-node scripts/generateImEnums.ts` */
export enum IMFilter {
  'Bartlett' = 'Bartlett',
  'Blackman' = 'Blackman',
  'Bohman' = 'Bohman',
  'Box' = 'Box',
  'Catrom' = 'Catrom',
  'Cosine' = 'Cosine',
  'Cubic' = 'Cubic',
  'Gaussian' = 'Gaussian',
  'Hamming' = 'Hamming',
  'Hann' = 'Hann',
  'Hermite' = 'Hermite',
  'Jinc' = 'Jinc',
  'Kaiser' = 'Kaiser',
  'Lagrange' = 'Lagrange',
  'Lanczos' = 'Lanczos',
  'Lanczos2' = 'Lanczos2',
  'Lanczos2Sharp' = 'Lanczos2Sharp',
  'LanczosRadius' = 'LanczosRadius',
  'LanczosSharp' = 'LanczosSharp',
  'Mitchell' = 'Mitchell',
  'Parzen' = 'Parzen',
  'Point' = 'Point',
  'Quadratic' = 'Quadratic',
  'Robidoux' = 'Robidoux',
  'RobidouxSharp' = 'RobidouxSharp',
  'Sinc' = 'Sinc',
  'SincFast' = 'SincFast',
  'Spline' = 'Spline',
  'CubicSpline' = 'CubicSpline',
  'Triangle' = 'Triangle',
  'Welch' = 'Welch',
}
