/* auto-generated file using command `npx ts-node scripts/generateImEnums.ts` */
export enum IMLogEvent {
  'All' = 'All',
  'Accelerate' = 'Accelerate',
  'Annotate' = 'Annotate',
  'Blob' = 'Blob',
  'Cache' = 'Cache',
  'Coder' = 'Coder',
  'Command' = 'Command',
  'Configure' = 'Configure',
  'Deprecate' = 'Deprecate',
  'Draw' = 'Draw',
  'Exception' = 'Exception',
  'Locale' = 'Locale',
  'Module' = 'Module',
  'None' = 'None',
  'Pixel' = 'Pixel',
  'Policy' = 'Policy',
  'Resource' = 'Resource',
  'Trace' = 'Trace',
  'Transform' = 'Transform',
  'User' = 'User',
  'Wand' = 'Wand',
  'X11' = 'X11',
}
