/* auto-generated file using command `npx ts-node scripts/generateImEnums.ts` */
export enum IMMorphology {
  'Correlate' = 'Correlate',
  'Convolve' = 'Convolve',
  'Dilate' = 'Dilate',
  'Erode' = 'Erode',
  'Close' = 'Close',
  'Open' = 'Open',
  'DilateIntensity' = 'DilateIntensity',
  'ErodeIntensity' = 'ErodeIntensity',
  'CloseIntensity' = 'CloseIntensity',
  'OpenIntensity' = 'OpenIntensity',
  'DilateI' = 'DilateI',
  'ErodeI' = 'ErodeI',
  'CloseI' = 'CloseI',
  'OpenI' = 'OpenI',
  'Smooth' = 'Smooth',
  'EdgeOut' = 'EdgeOut',
  'EdgeIn' = 'EdgeIn',
  'Edge' = 'Edge',
  'TopHat' = 'TopHat',
  'BottomHat' = 'BottomHat',
  'Hmt' = 'Hmt',
  'HitNMiss' = 'HitNMiss',
  'HitAndMiss' = 'HitAndMiss',
  'Thinning' = 'Thinning',
  'Thicken' = 'Thicken',
  'Distance' = 'Distance',
  'IterativeDistance' = 'IterativeDistance',
}
