/* auto-generated file using command `npx ts-node scripts/generateImEnums.ts` */
export enum IMPixelChannel {
  'Undefined' = 'Undefined',
  'A' = 'A',
  'Alpha' = 'Alpha',
  'B' = 'B',
  'Bk' = 'Bk',
  'Black' = 'Black',
  'Blue' = 'Blue',
  'Cb' = 'Cb',
  'Composite' = 'Composite',
  'CompositeMask' = 'CompositeMask',
  'C' = 'C',
  'Cr' = 'Cr',
  'Cyan' = 'Cyan',
  'Gray' = 'Gray',
  'G' = 'G',
  'Green' = 'Green',
  'Index' = 'Index',
  'Intensity' = 'Intensity',
  'K' = 'K',
  'M' = 'M',
  'Magenta' = 'Magenta',
  'Meta' = 'Meta',
  'O' = 'O',
  'R' = 'R',
  'ReadMask' = 'ReadMask',
  'Red' = 'Red',
  'Sync' = 'Sync',
  'WriteMask' = 'WriteMask',
  'Y' = 'Y',
  'Yellow' = 'Yellow',
}
