/* auto-generated file using command `npx ts-node scripts/generateImEnums.ts` */
export enum IMPreview {
  'AddNoise' = 'AddNoise',
  'Blur' = 'Blur',
  'Brightness' = 'Brightness',
  'Charcoal' = 'Charcoal',
  'Despeckle' = 'Despeckle',
  'Dull' = 'Dull',
  'EdgeDetect' = 'EdgeDetect',
  'Gamma' = 'Gamma',
  'Grayscale' = 'Grayscale',
  'Hue' = 'Hue',
  'Implode' = 'Implode',
  'JPEG' = 'JPEG',
  'OilPaint' = 'OilPaint',
  'Quantize' = 'Quantize',
  'Raise' = 'Raise',
  'ReduceNoise' = 'ReduceNoise',
  'Roll' = 'Roll',
  'Rotate' = 'Rotate',
  'Saturation' = 'Saturation',
  'Segment' = 'Segment',
  'Shade' = 'Shade',
  'Sharpen' = 'Sharpen',
  'Shear' = 'Shear',
  'Solarize' = 'Solarize',
  'Spiff' = 'Spiff',
  'Spread' = 'Spread',
  'Swirl' = 'Swirl',
  'Threshold' = 'Threshold',
  'Wave' = 'Wave',
}
